### ISSUE TITLE
api for creating product types

### ISSUE THREAD

**Issue by DankiCalamari** [wisepythagoras/pos-system#1]
hi, I was just wondering how to use the api to create product types and where I would find a auth token

**Comment by wisepythagoras** [comment]
Hello! So, there are some instructions in the example configuration yaml file ([here](https://github.com/wisepythagoras/pos-system/blob/main/config.example.yaml)) for the token. As for the endpoint `/api/product/type`, it's a PUT and it takes a name and a title as its parameters, so you should be able to write a curl like this:
```sh
curl -X PUT [domain]/api/product/type -H 'proper auth here' -d 'name=blah&title=blah'
```

Refer to [this example](https://github.com/wisepythagoras/pos-system/blob/8deef59ce8ed4d5515b2c968f424f3b8390e5e9b/README.md?plain=1#L63)

**Comment by DankiCalamari** [comment]
Ive done the curl command above and changed the necessary fields but it isn't coming up with any product types when I try to make a products

**Comment by wisepythagoras** [comment]
If you visit the admin page and navigate to the products tab, do you see the product type in the list when you try to create a new product?

**Comment by DankiCalamari** [comment]
no

**Comment by wisepythagoras** [comment]
Please paste the response you get from the curl

**Comment by DankiCalamari** [comment]
<img width="871" alt="Screen Shot 2023-07-26 at 11 50 00 am" src="https://github.com/wisepythagoras/pos-system/assets/72004695/6828569b-c69e-4cb9-bd65-37c6f8ee62cb">

**Comment by DankiCalamari** [comment]
<img width="871" alt="Screen Shot 2023-07-26 at 11 50 00 am" src="https://github.com/wisepythagoras/pos-system/assets/72004695/6cd8992d-5531-4032-be70-30757e459025">

**Comment by wisepythagoras** [comment]
So, that's the server log, not the curl result, but from the 403 it looks like you're not authenticating correctly. Make sure you're passing the correct token to `x-auth-token` (which is case sensitive)

**Comment by DankiCalamari** [comment]
I didn't get a result from the curl command

**Comment by DankiCalamari** [comment]
do I need to put the actual word or the Sha

**Comment by wisepythagoras** [comment]
Like I have it in the example I posted in my initial comment

https://github.com/wisepythagoras/pos-system/blob/8deef59ce8ed4d5515b2c968f424f3b8390e5e9b/README.md?plain=1#L63

**Comment by DankiCalamari** [comment]
there is no result for the curl command but the server log keeps saying 403 on the PUT

**Comment by wisepythagoras** [comment]
So, just as a test I added the following random values in my config:

``` yaml
server:
    port: 8089

admin:
    username: admin
    password: 7bb78625cd5ddf22dea63cc04db8b6ce51c3c86bbd99d836a6f1bff82527ce15f4337f416276f03cb0568e032d6a723600aaea12a5667e595d81fd74a43ebe52
    token: f45617945f7f89deb81173f0bd29fde37b698d9cd1cc7a99fb3fa3c189241ce7

secret: "a simple test"
key: "F^Aw9IxvGYXC&Kn85x_VWX6Iamt^MXav"
```

And then I ran the following:

``` sh
curl -X PUT http://127.0.0.1:8089/api/product/type -d 'name=Test&title=Test%20Product%20Type' -H 'x-auth-token: f45617945f7f89deb81173f0bd29fde37b698d9cd1cc7a99fb3fa3c189241ce7'
```
And I received the following:
``` json
{"data":null,"success":true,"error":""}
```

I then ran the following to verify:

``` sh
curl http://127.0.0.1:8089/api/product/types
```

And received the list:

``` json
{
  "data": [
    {
      "id": 1,
      "name": "Test",
      "title": "Test Product Type"
    }
  ],
  "success": true,
  "error": ""
}
```

You might not be authenticating correctly, because the code works as expected here

**Comment by DankiCalamari** [comment]
that worked

**Comment by DankiCalamari** [comment]
now when i do the curl post to create products it comes back with the {"data":null,"success":true,"error":""} as the response but theres no products coming up and when i curl http://127.0.0.1:8088/api/product/ its saying that the page has moved permanently

**Comment by wisepythagoras** [comment]
The appropriate endpoint is the following:

https://github.com/wisepythagoras/pos-system/blob/8deef59ce8ed4d5515b2c968f424f3b8390e5e9b/main.go#L172

Also, you can just use the admin page to create products

**Comment by DankiCalamari** [comment]
it doesnt work when i go to the admin page to create products
